// src/web/src/app/features/main-menu/main-menu.component.ts
import { Component } from '@angular/core';
import { MenuButtonComponent } from '../../shared/buttons/menu-button.component';
import { Route, Router } from '@angular/router';

@Component({
  selector: 'app-main-menu',
  standalone: true,
  imports: [MenuButtonComponent],
  templateUrl: './main-menu.component.html',
  styleUrl: './main-menu.component.css',
})
export class MainMenuComponent {
  constructor(private router: Router) { }

  onCreateGame() {
    const roomId = this.generateGameCode();
    this.router.navigate([`/${roomId}`])
    console.log('Create Game clicked');
    // Add your logic here
  }

  onJoinGame() {
    console.log('Join Game clicked');
    // Add your logic here
  }

  onViewCharacters() {
    console.log('View Characters clicked');
    // Add your logic here
  }

  /**
   *Create a random game code used to joing a room
   * @param length - defaults to 6 digits
   * @returns
   */
  private generateGameCode(length: number = 6): string {
    const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    let result = '';
    for (let i = 0; i < length; i++) {
      const randomIndex = Math.floor(Math.random() * characters.length);
      result += characters[randomIndex];
    }
    return result;
  }

}

<div class="relative bg-opacity-50 container flex-col items-center justify-center gap-8 px-4 py-16 p-6 flex space-x-4 w-96 mx-auto bg-[#2e2e2e] rounded-[12px]">
  <h1 class="text-6xl font-extrabold tracking-tight text-white ">DuelScape</h1>
  <div class="flex space-x-4">
      <app-menu-button (buttonClick)="onCreateGame()">Create Game</app-menu-button>
      <app-menu-button (buttonClick)="onJoinGame()">Join Game</app-menu-button>
  </div>
  <app-menu-button (buttonClick)="onViewCharacters()">View Characters</app-menu-button>
</div>

// client/src/components/Menus/MainMenu.tsx
import { generateGameCode } from '../../lib/utils.ts';
import { MenuButton } from '../Shared/MenuButton.tsx';
import { Footer } from './Footer.tsx';
import { useNavigate } from 'react-router-dom';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { Room } from './Room.tsx';

export const MainMenu = () => {
    const navigate = useNavigate();
    /**
     * TODO: Placeholder for Join Game Logic.
     *   This should show a screen where the player can enter in a game code to join a create game
     */
    const OnJoinGame = () => {
        console.log('Join Game');
    };

    /**
     * Generates a random gamecode to be used as the roomId.
     * Naviagtes to the Room to setup the SignalR connection.
     * 
     * {@link Room}
     */
    const OnCreateGame = () => {
        const roomId = generateGameCode();
        navigate(`/${roomId}`);
    };

    /**
     * TODO: Placeholder for View Characters logic.
     *   This should go to a screen that has all available characters and their decks.
     */
    const OnViewCharacters = () => {
        console.log('View Characters');
    };

    return (
        <div className="relative bg-opacity-50 container flex-col items-center justify-center gap-8 px-4 py-16  p-6 flex space-x-4 w-96 mx-auto bg-[#2e2e2e] rounded-[12px]">
            <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[4rem]">DuelScape</h1>
            <div className="flex space-x-4 ">
                <MenuButton onClick={() => OnCreateGame()}>Create Game</MenuButton>
                <MenuButton onClick={() => OnJoinGame()}>Join Game</MenuButton>
            </div>

            <MenuButton onClick={() => OnViewCharacters()}>View Characters</MenuButton>
            <Footer />
        </div>
    );
};
