// src/web/src/app/features/room/room.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { HubConnection, HubConnectionState, HubConnectionBuilder, HttpTransportType, LogLevel } from '@microsoft/signalr';
import { v4 as uuid } from 'uuid';
import { CommonModule } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
import { switchMap } from 'rxjs';
import { environment } from '../../../environments/environment';
import { LobbyBaseComponent } from '../lobby/lobby-base/lobby-base.component';
import { GameState } from '../game/models/game-state.interface';


@Component({
  selector: 'app-room',
  standalone: true,
  imports: [LobbyBaseComponent, CommonModule],
  templateUrl: './room.component.html',
  styleUrl: './room.component.css'
})
export class RoomComponent implements OnInit, OnDestroy {
  persistentId: string;
  roomId: string = '';
  connection: HubConnection | undefined;
  connectionError: string | undefined;
  gameState: GameState | undefined;

  constructor(private route: ActivatedRoute) {
    this.persistentId = localStorage.getItem('persistentId') ?? uuid();
  }

  ngOnInit() {
    this.route.paramMap.subscribe(params => {
      const roomIdParam = params.get('roomId')
      this.roomId = roomIdParam ? roomIdParam : '';
      if (this.roomId && this.persistentId) {
        if (this.connection?.state === HubConnectionState.Connected) {
          this.connection?.stop();
        }
        this.createConnection();
      }
    });
  }

  ngOnDestroy() {
    this.connection?.off('UpdateGameState', this.updateGameState);
    this.connection?.stop();
  }

  createConnection() {
    const hubUrl = `${environment.apiUrl}/server`;
    console.log('connecting to: ', hubUrl);

    const signalRConnection = new HubConnectionBuilder()
      .withUrl(hubUrl, {
        skipNegotiation: true,
        transport: HttpTransportType.WebSockets,
        accessTokenFactory: () => this.persistentId,
      })
      .configureLogging(LogLevel.Information)
      .build();

    signalRConnection
      .start()
      .then(() => {
        this.connection = signalRConnection;
        this.connectionStatusUpdated();
      })
      .catch((e) => {
        console.log(e);
        this.connectionError = 'Could not connect to the server';
      });
  }

  connectionStatusUpdated() {
    if (!this.connection) return;

    switch (this.connection.state) {
      case HubConnectionState.Connected:
        this.connection.onclose((error) => {
          if (error) {
            this.connectionStatusUpdated();
            this.connection = undefined;
            this.createConnection();
          } else {
            this.connection?.off('UpdateGameState', this.updateGameState);
          }
        });
        this.connection.on('UpdateGameState', this.updateGameState.bind(this));
        this.joinRoom();
        break;
      case HubConnectionState.Disconnected:
        this.connection.off('UpdateGameState', this.updateGameState.bind(this));
        break;
      default:
        break;
    }
  }

  joinRoom() {
    if (this.roomId) {
      this.connection?.invoke('JoinRoom', this.roomId);
    }
  }

  updateGameState(updatedGameState: GameState) {
    this.gameState = { ...updatedGameState };
    console.log(this.gameState);
  }

  // Placeholder method for getting the room ID
  useRoomId(): string {
    // Implement your logic to get the room ID
    return 'some-room-id';
  }
}

<!-- <div *ngIf="!gameState; else lobbyTemplate">
    <app-lobby-base
        [roomId]="roomId"
        [connection]="connection"
        [playerId]="persistentId"
        [gameState]="gameState"
        (onBack)="connection?.stop()"
        [connectionError]="connectionError"
    ></app-lobby-base>
</div>
<ng-template #lobbyTemplate>
    <app-lobby-base
        [roomId]="roomId"
        [connection]="connection"
        [playerId]="persistentId"
        [gameState]="gameState"
        (onBack)="connection?.stop()"
        [connectionError]="connectionError"
    ></app-lobby-base>
</ng-template> -->

<app-lobby-base
    [roomId]="roomId"
    [connection]="connection"
    [playerId]="persistentId"
    [gameState]="gameState"
    (onBack)="connection?.stop()"
    [connectionError]="connectionError"
></app-lobby-base>

// client/src/components/Menus/Room.tsx
import { useState, useEffect } from 'react';
import { config } from '../../config';
import { useRoomId } from '../../hooks/useRoomId';
import { v4 as uuid } from 'uuid';
import useStateRef from 'react-usestateref';
import {
    HttpTransportType,
    HubConnection,
    HubConnectionBuilder,
    HubConnectionState,
    LogLevel,
} from '@microsoft/signalr';
import { GameState } from '../../interfaces/game-state.interface';
import { Lobby } from './Lobby/Lobby';

/**
 * Base Component for the Lobby and the Game.
 * Will create the SinglaR connection
 * @returns
 */
export const Room = () => {
    const [persistentId] = useState<string>(() => localStorage.getItem('persistentId') ?? uuid());
    const [roomId, roomIdRef] = useRoomId();
    const [connection, setConnection, connectionRef] = useStateRef<HubConnection>();
    const [connectionError, setConnectionError] = useState<string>();
    const [gameState, setGameState] = useState<GameState>();

    useEffect(() => {
        if (roomId && persistentId) {
            if (connectionRef.current?.state === HubConnectionState.Connected) {
                connectionRef.current?.stop();
            }
            CreateConnection();
        }
    }, [roomId, persistentId, connectionRef]);

    /**
     * Creates the SignalR connection to the backend.
     */
    const CreateConnection = () => {
        const hubUrl = `${config.api}/server`;
        console.log('connecting to: ', hubUrl);
        // Builds the SignalR connection, mapping it to /server
        const signalRConnection = new HubConnectionBuilder()
            .withUrl(hubUrl, {
                skipNegotiation: true,
                transport: HttpTransportType.WebSockets,
                accessTokenFactory: () => persistentId,
            })
            .configureLogging(LogLevel.Information)
            .build();

        signalRConnection
            ?.start()
            .then(() => {
                setConnection(signalRConnection);
                ConnectionStatusUpdated();
            })
            .catch((e) => {
                console.log(e);
                setConnectionError('Could not connect to the server');
            });
    };

    /**
     * Perfoms actions when the connection status is updated.
     */
    const ConnectionStatusUpdated = () => {
        switch (connectionRef.current?.state) {
            case HubConnectionState.Connected:
                connectionRef.current?.onclose((error) => {
                    if (error) {
                        ConnectionStatusUpdated();
                        setConnection(undefined);
                        CreateConnection();
                    } else {
                        connectionRef.current?.off('UpdateGameState', UpdateGameState);
                    }
                });
                connectionRef.current?.on('UpdateGameState', UpdateGameState);
                JoinRoom();

                break;
            case HubConnectionState.Disconnected:
                connectionRef.current?.off('UpdateGameState', UpdateGameState);
                break;
            default:
                break;
        }
    };

    /**
     * Joins a room with an existing connection
     * @returns
     */
    const JoinRoom = () => {
        if (roomIdRef?.current) {
            connectionRef.current?.invoke('JoinRoom', roomIdRef?.current);
        }
    };

    /**
     * Update the game state from the websocket connection.
     * @param updatedGameState
     */
    const UpdateGameState = (updatedGameState: GameState) => {
        setGameState({ ...updatedGameState });
        console.log(gameState);
    };

    return (
        <>
            {!!gameState && <div>Game</div>}

            <Lobby
                roomId={roomId}
                connection={connection}
                playerId={persistentId}
                gameState={gameState}
                onBack={() => connection?.stop}
                connectionError={connectionError}
            ></Lobby>
        </>
    );
};
