// src/web/src/app/shared/menu-header/menu-header.component.ts
import { Component, Input } from '@angular/core';
import { Router } from '@angular/router';
import { HomeButtonComponent } from "../buttons/home-button.component";

@Component({
  selector: 'app-menu-header',
  standalone: true,
  imports: [HomeButtonComponent],
  templateUrl: './menu-header.component.html',
  styleUrl: './menu-header.component.css'
})
export class MenuHeaderComponent {
  @Input() children!: string;

  constructor(private router: Router) { }

  navigateHome() {
    this.router.navigate(['/']);
  }
}

<div class="absolute left-0 top-0 bg-gray-700 p-4 rounded-t-[12px] flex items-center justify-between w-full">
    <app-home-button (click)="navigateHome()"></app-home-button>
    <div class="flex-1 text-center">
        <h1 class="text-white sm:text-[2rem] text-center">{{ children }}</h1>
    </div>
</div>

// src/react/src/components/Menus/MenuHeader.tsx
import { useNavigate } from 'react-router-dom';
import { HomeButton } from '../Shared/Buttons';

interface MenuHeaderProps {
    children: string;
}

export const MenuHeader = ({ children }: MenuHeaderProps) => {
    const navigate = useNavigate();
    return (
        <div className=" absolute left-0 top-0 bg-gray-700 p-4 rounded-t-[12px] flex items-center justify-between w-full ">
            <HomeButton onClick={() => navigate('/')} />
            <div className="flex-1 text-center">
                <h1 className="text-white sm:text-[2rem] text-center">{children}</h1>
            </div>
        </div>
    );
};
